import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="min-h-screen flex flex-col">
				{/* Toaster */}

				{/* Header */}
				<header className="border-b sticky top-0 z-50">
					<Header />
				</header>

				<div className="bg-[#F4F2ED] flex-1 w-full">
					<main>{children}</main>
				</div>
			</body>
		</html>
	);
}
